"""Static HTML citations digest — grouped by which lab paper is cited, then by month.

Generated by the weekly lab-watch run and published to GitHub Pages, since
citations aren't posted to Slack yet (too noisy) — this is the "see them"
link instead. Styling mirrors the ourak frontend's design tokens
(frontend/src/styles/globals.css) so it reads as the same product, even
though this is a plain static file with no React/build step involved.

Usage:
    python -m app.citations_page > site/index.html
"""

import html
import json
import os
from collections import defaultdict
from datetime import datetime, timezone

from sqlmodel import Session, select

from app.config import load_env
from app.db import PaperDB, PaperTopicLink, TopicDB, init_db
from app.lab_watch import CITING_TOPIC, load_lab_config

_UNSPECIFIED = "Other lab work"
_UNKNOWN_MONTH = "Undated"


def _citing_papers(session: Session, topic_name: str) -> list[PaperDB]:
    topic = session.exec(select(TopicDB).where(TopicDB.name == topic_name)).first()
    if not topic:
        return []
    return session.exec(
        select(PaperDB)
        .join(PaperTopicLink, PaperDB.id == PaperTopicLink.paper_id)
        .where(PaperTopicLink.topic_id == topic.id)
        .order_by(PaperDB.published_date.desc())
    ).all()


def _month_key(paper: PaperDB) -> tuple[str, str]:
    """(sort_key, label) for the paper's publication month, e.g. ("2026-09", "September 2026")."""
    date = paper.published_date or ""
    try:
        parsed = datetime.strptime(date[:7], "%Y-%m")
        return parsed.strftime("%Y-%m"), parsed.strftime("%B %Y")
    except ValueError:
        return "0000-00", _UNKNOWN_MONTH


def _group_by_cited_work(papers: list[PaperDB]) -> list[tuple[dict, list[PaperDB]]]:
    """Group citing papers by which lab work they cite.

    Returns [(cited_work_info, citing_papers), ...] where cited_work_info is
    {"title", "authors", "published_date"} — whichever citing paper's record
    of it we saw first (they should all agree; it's the same lab paper).
    """
    order: list[str] = []
    info_by_title: dict[str, dict] = {}
    papers_by_title: dict[str, list[PaperDB]] = defaultdict(list)
    for paper in papers:
        works = json.loads(paper.cited_lab_works or "[]") or [{"title": _UNSPECIFIED}]
        for work in works:
            title = work.get("title") or _UNSPECIFIED
            if title not in info_by_title:
                info_by_title[title] = work
                order.append(title)
            papers_by_title[title].append(paper)
    groups = [(info_by_title[t], papers_by_title[t]) for t in order]
    return sorted(groups, key=lambda kv: len(kv[1]), reverse=True)


def _authors_et_al(authors: list[str], max_n: int = 3) -> str:
    if not authors:
        return ""
    return ", ".join(authors[:max_n]) + (" et al." if len(authors) > max_n else "")


def _group_by_month(papers: list[PaperDB]) -> list[tuple[str, list[PaperDB]]]:
    months: dict[str, tuple[str, list[PaperDB]]] = {}
    for paper in papers:
        sort_key, label = _month_key(paper)
        months.setdefault(sort_key, (label, []))[1].append(paper)
    return [months[k] for k in sorted(months, reverse=True)]


def _count_label(n: int, noun: str = "citation") -> str:
    return f"{n} {noun}{'s' if n != 1 else ''}"


def _paper_row(paper: PaperDB) -> str:
    title = html.escape(paper.title or "Untitled")
    link = f'<a href="{html.escape(paper.url)}">{title}</a>' if paper.url else title

    authors = json.loads(paper.authors or "[]")
    meta = " · ".join(p for p in [_authors_et_al(authors), paper.journal, paper.published_date] if p)

    return (
        '<li class="row">'
        f'<div class="rowTitle">{link}</div>'
        f'<div class="rowMeta">{html.escape(meta)}</div>'
        "</li>"
    )


def _group_html(cited_work: dict, papers: list[PaperDB]) -> str:
    """One bordered card per cited lab paper — the box makes 'what's under what' unambiguous."""
    title = cited_work.get("title") or _UNSPECIFIED
    meta = " · ".join(
        p for p in [_authors_et_al(cited_work.get("authors") or []), cited_work.get("published_date")] if p
    )
    meta_html = f'<div class="groupMeta">{html.escape(meta)}</div>' if meta else ""

    return (
        '<div class="group">'
        '<div class="groupHeader">'
        '<div class="groupHeaderTop">'
        '<span class="citesLabel">Cites</span>'
        f'<span class="groupTitle">{html.escape(title)}</span>'
        f'<span class="groupCount">{_count_label(len(papers))}</span>'
        "</div>"
        f"{meta_html}"
        "</div>"
        f'<ul class="groupList">{"".join(_paper_row(p) for p in papers)}</ul>'
        "</div>"
    )


def _month_html(label: str, papers: list[PaperDB], *, open_by_default: bool) -> str:
    groups = _group_by_cited_work(papers)
    # Groups with several citations are the interesting ones — show them right away.
    # One-citation groups are usually the majority and mostly noise; tuck them
    # behind their own toggle so a month doesn't turn into an endless scroll.
    highlighted = [(t, g) for t, g in groups if len(g) > 1]
    singles = [(t, g) for t, g in groups if len(g) == 1]

    highlighted_html = "\n".join(_group_html(title, group) for title, group in highlighted)
    singles_html = ""
    if singles:
        singles_html = (
            '<details class="singleWrap">'
            f'<summary><span class="chevron">&#9656;</span> {len(singles)} more, cited once each &mdash; show</summary>'
            f'<div class="singleBody">{"".join(_group_html(t, g) for t, g in singles)}</div>'
            "</details>"
        )

    return (
        f'<details class="month"{" open" if open_by_default else ""}>'
        f'<summary class="monthHeading"><span class="chevron">&#9656;</span> {html.escape(label)} '
        f'<span class="monthCount">{_count_label(len(papers))}</span></summary>'
        f'<div class="monthBody">{highlighted_html}{singles_html}</div>'
        "</details>"
    )


def build_citations_page(session: Session, lab_name: str, topic_name: str = CITING_TOPIC) -> str:
    """Render the full static HTML page: months (newest first), each grouped by cited work."""
    papers = _citing_papers(session, topic_name)
    lab = html.escape(lab_name)

    if papers:
        months = _group_by_month(papers)
        body = "\n".join(
            _month_html(label, month_papers, open_by_default=(i == 0))
            for i, (label, month_papers) in enumerate(months)
        )
        subtitle = f"{_count_label(len(papers))} of {lab}'s work, grouped by month then by which paper is cited."
    else:
        body = '<p class="empty">No citations tracked yet — check back after the next weekly run.</p>'
        subtitle = "Nothing tracked yet."

    updated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>{lab} Citations Digest</title>
<style>
{_STYLE}
</style>
</head>
<body>
<header class="topbar">
  <div class="logo">ourak<span>.</span></div>
  <div class="topbarRight">Citations Digest</div>
</header>
<main class="content">
  <h1>Who's citing {lab}</h1>
  <p class="subtitle">{subtitle}</p>
  {body}
  <div class="updated">Updated {updated}</div>
</main>
</body>
</html>"""


# Design tokens copied from frontend/src/styles/globals.css and
# frontend/src/components/{Header,PaperCard}.module.css, dark-first to match
# the app's default theme, with a light override for prefers-color-scheme.
_STYLE = """
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap');

  :root {
    --color-bg: #0f1117;
    --color-surface: #1a1d27;
    --color-border: #2a2d3a;
    --color-text-primary: #e4e5e9;
    --color-text-secondary: #9ca0ad;
    --color-text-muted: #6b7084;
    --color-accent: #3b82f6;
    --color-accent-hover: #60a5fa;
    --radius-sm: 4px;
    --radius-md: 8px;
    --shadow-sm: 0 1px 3px rgba(0, 0, 0, 0.3);
    color-scheme: dark;
  }
  @media (prefers-color-scheme: light) {
    :root {
      --color-bg: #f8f9fa;
      --color-surface: #ffffff;
      --color-border: #e2e4e9;
      --color-text-primary: #1a1d27;
      --color-text-secondary: #5f6368;
      --color-text-muted: #9ca0ad;
      --color-accent: #2563eb;
      --color-accent-hover: #1d4ed8;
      --shadow-sm: 0 1px 3px rgba(0, 0, 0, 0.08);
      color-scheme: light;
    }
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: 'Inter', system-ui, -apple-system, sans-serif;
    background: var(--color-bg);
    color: var(--color-text-primary);
    -webkit-font-smoothing: antialiased;
  }
  a { color: var(--color-accent); text-decoration: none; }
  a:hover { text-decoration: underline; }

  .topbar {
    position: sticky; top: 0; z-index: 10; height: 56px;
    display: flex; align-items: center; justify-content: space-between;
    padding: 0 24px; background: var(--color-surface); border-bottom: 1px solid var(--color-border);
  }
  .logo { font-size: 18px; font-weight: 600; letter-spacing: -0.02em; }
  .logo span { color: var(--color-accent); }
  .topbarRight { font-size: 13px; color: var(--color-text-secondary); }

  .content { max-width: 780px; margin: 0 auto; padding: 32px 24px 64px; }
  h1 { font-size: 22px; font-weight: 600; margin-bottom: 6px; }
  .subtitle { font-size: 13px; color: var(--color-text-secondary); margin-bottom: 32px; }

  .month { margin-top: 40px; }
  .month:first-of-type { margin-top: 8px; }
  .monthHeading {
    display: flex; align-items: center; gap: 8px; cursor: pointer; list-style: none;
    font-size: 15px; font-weight: 600; color: var(--color-text-primary);
    padding-bottom: 8px; margin-bottom: 16px; border-bottom: 1px solid var(--color-border);
  }
  .monthHeading::-webkit-details-marker { display: none; }
  .monthHeading::marker { content: ""; }
  .monthHeading:hover { color: var(--color-accent); }
  .monthCount { font-weight: 400; font-size: 12px; color: var(--color-text-muted); }
  .chevron { display: inline-block; transition: transform 150ms ease; color: var(--color-text-muted); font-size: 11px; }
  details[open] > .monthHeading .chevron { transform: rotate(90deg); }
  .monthBody { padding-top: 4px; }

  .singleWrap {
    margin-top: 4px; margin-bottom: 16px;
  }
  .singleWrap summary {
    display: flex; align-items: center; gap: 6px; cursor: pointer; list-style: none;
    font-size: 13px; color: var(--color-text-muted); padding: 10px 4px;
    border-top: 1px dashed var(--color-border);
  }
  .singleWrap summary::-webkit-details-marker { display: none; }
  .singleWrap summary::marker { content: ""; }
  .singleWrap summary:hover { color: var(--color-text-secondary); }
  .singleWrap .chevron { font-size: 10px; }
  .singleWrap[open] > summary .chevron { transform: rotate(90deg); }
  .singleBody { margin-top: 8px; }

  .group {
    background: var(--color-surface); border: 1px solid var(--color-border);
    border-radius: var(--radius-md); box-shadow: var(--shadow-sm);
    margin-bottom: 16px; overflow: hidden;
  }
  .groupHeader {
    padding: 10px 16px; background: rgba(59, 130, 246, 0.08);
    border-bottom: 1px solid var(--color-border);
  }
  .groupHeaderTop { display: flex; align-items: baseline; gap: 8px; flex-wrap: wrap; }
  .groupMeta { font-size: 12px; color: var(--color-text-secondary); margin-top: 4px; }
  .citesLabel {
    font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em;
    color: var(--color-accent); background: rgba(59, 130, 246, 0.15);
    padding: 2px 6px; border-radius: var(--radius-sm);
  }
  .groupTitle { font-size: 14px; font-weight: 600; flex: 1; min-width: 0; }
  .groupCount { font-size: 12px; color: var(--color-text-muted); white-space: nowrap; }

  .groupList { list-style: none; }
  .row { padding: 12px 16px; border-bottom: 1px solid var(--color-border); }
  .row:last-child { border-bottom: none; }
  .rowTitle { font-size: 14px; font-weight: 500; }
  .rowTitle a { color: var(--color-text-primary); }
  .rowTitle a:hover { color: var(--color-accent); }
  .rowMeta { font-size: 12px; color: var(--color-text-secondary); margin-top: 3px; }

  .empty { color: var(--color-text-muted); font-size: 14px; padding: 48px 0; text-align: center; }
  .updated { font-size: 11px; color: var(--color-text-muted); margin-top: 48px; }
"""


def main() -> None:
    load_env()
    cfg = load_lab_config(os.getenv("LAB_CONFIG", "config/lab.yaml"))
    db_url = os.getenv("DATABASE_URL") or "sqlite:///data/paperwatch.db"
    engine = init_db(db_url)
    with Session(engine) as session:
        print(build_citations_page(session, cfg.lab_name))


if __name__ == "__main__":
    main()
